development: &default
  adapter: postgresql
  database: stuk
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: stuk_test

production:
  <<: *default
  database: stuk_production